version: '3'
services:
    server:
        build:
            context: ./server
            target: build
        image: server
        command: reflex -r "\.go$$" -s -- sh -c "go run ./"
        ports:
            - 8080:8080
        volumes:
            - ./server/:/src
    ui:
        build: ./ui
        command: npm run start
        ports:
            - 3000:3000
        volumes:
            - ./ui/:/src
            - ./ui/node_modules:/src/node_modules

volumes:
    nodemodules: {}
